package kreditniodjel.isplatastambenogkredita;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Osoba implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Osoba() {
    }

}