package kreditniodjel.isplatastambenogkredita;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Produkt implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Produkt() {
    }

}