package kreditniodjel.isplatastambenogkredita;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Zahtjev implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Zahtjev ID")
   private java.lang.Long zahtjev_ID;
   @org.kie.api.definition.type.Label(value = "Korisnik ID")
   private java.lang.Long korisnik_ID;
   @org.kie.api.definition.type.Label(value = "Produkt_ID")
   private java.lang.Long produkt_ID;
   @org.kie.api.definition.type.Label(value = "Ugovorna svota")
   private java.math.BigDecimal ugovornaSvota;
   @org.kie.api.definition.type.Label(value = "Iznos rate")
   private java.math.BigDecimal iznosRate;
   @org.kie.api.definition.type.Label(value = "Ispravan")
   private java.lang.Boolean jeIspravan;
   @org.kie.api.definition.type.Label(value = "Datum")
   private java.util.Date datum;

   public Zahtjev()
   {
   }

   public java.lang.Long getZahtjev_ID()
   {
      return this.zahtjev_ID;
   }

   public void setZahtjev_ID(java.lang.Long zahtjev_ID)
   {
      this.zahtjev_ID = zahtjev_ID;
   }

   public java.lang.Long getKorisnik_ID()
   {
      return this.korisnik_ID;
   }

   public void setKorisnik_ID(java.lang.Long korisnik_ID)
   {
      this.korisnik_ID = korisnik_ID;
   }

   public java.lang.Long getProdukt_ID()
   {
      return this.produkt_ID;
   }

   public void setProdukt_ID(java.lang.Long produkt_ID)
   {
      this.produkt_ID = produkt_ID;
   }

   public java.math.BigDecimal getUgovornaSvota()
   {
      return this.ugovornaSvota;
   }

   public void setUgovornaSvota(java.math.BigDecimal ugovornaSvota)
   {
      this.ugovornaSvota = ugovornaSvota;
   }

   public java.math.BigDecimal getIznosRate()
   {
      return this.iznosRate;
   }

   public void setIznosRate(java.math.BigDecimal iznosRate)
   {
      this.iznosRate = iznosRate;
   }

   public java.lang.Boolean getJeIspravan()
   {
      return this.jeIspravan;
   }

   public void setJeIspravan(java.lang.Boolean jeIspravan)
   {
      this.jeIspravan = jeIspravan;
   }

   public java.util.Date getDatum()
   {
      return this.datum;
   }

   public void setDatum(java.util.Date datum)
   {
      this.datum = datum;
   }

   public Zahtjev(java.lang.Long zahtjev_ID, java.lang.Long korisnik_ID,
         java.lang.Long produkt_ID, java.math.BigDecimal ugovornaSvota,
         java.math.BigDecimal iznosRate, java.lang.Boolean jeIspravan,
         java.util.Date datum)
   {
      this.zahtjev_ID = zahtjev_ID;
      this.korisnik_ID = korisnik_ID;
      this.produkt_ID = produkt_ID;
      this.ugovornaSvota = ugovornaSvota;
      this.iznosRate = iznosRate;
      this.jeIspravan = jeIspravan;
      this.datum = datum;
   }

}